[package]
name = "bevy_template"
version = "0.1.0"
authors = ["8bit <8bittd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
rand = "0.8.3"